[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --alluredir=reports/allure-results
    --reruns=2
    --reruns-delay=1
    --capture=tee-sys
markers =
    smoke: smoke tests
    regression: regression tests
    critical: critical path tests
